version: '3.8'

services:
  frontend:
    # Nombre del contenedor
    container_name: portfolio-front
    
    # Construir usando el Dockerfile del directorio actual
    build:
      context: .
      dockerfile: Dockerfile
    
    # Reiniciar siempre si falla
    restart: always

